// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/biohuns/discord-servertool/entity"
	"github.com/biohuns/discord-servertool/service/config"
	"github.com/biohuns/discord-servertool/service/discord"
	"github.com/biohuns/discord-servertool/service/gcp"
)

// Injectors from injector.go:

func initializeMessageService() (entity.MessageService, error) {
	configService, err := config.NewService()
	if err != nil {
		return nil, err
	}
	instanceService, err := gcp.NewService(configService)
	if err != nil {
		return nil, err
	}
	messageService, err := discord.NewService(configService, instanceService)
	if err != nil {
		return nil, err
	}
	return messageService, nil
}
