name: Build

on:
  push:
    branches:
      - "*"
    tags:
      - "*"

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      APP: discord-servertool
    steps:

      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14

      - name: Check out
        uses: actions/checkout@v1

      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d'/' -f3)

      - name: Build binary
        run: |
          export PATH=$(go env GOPATH)/bin:$PATH
          make build

      - name: Create config.json
        run: echo '${{ secrets.CONFIG }}' > config.json

      - name: Create credential.json
        run: echo '${{ secrets.CREDENTIAL }}' > credential.json

      - name: Archive source
        run: |
          mkdir -p ${{ env.APP }}-${{ steps.get_version.outputs.VERSION }} SOURCES
          cp ${{ env.APP }} \
            config.json \
            credential.json \
            systemd.service \
            ${{ env.APP }}-${{ steps.get_version.outputs.VERSION }}/
          tar czf \
            SOURCES/${{ env.APP }}-${{ steps.get_version.outputs.VERSION }}.tar.gz \
            ${{ env.APP }}-${{ steps.get_version.outputs.VERSION }}/

      - name: Build RPM
        uses: ./.github/actions/rpmbuild

      # TODO SSH Deploy
